server:
  port : 8071
logging:
  level:
    .: error
    org.springframework: ERROR
    me.bubbleinvestor: TRACE
spring:
  kafka:
    bootstrap-servers: "127.0.0.1:9092"
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
kafka:
  topic:
    name: test1
  group:
    id: inferenceengine
  bootstrap:
    servers: "127.0.0.1:9092"