version: '3'
services:
# TODO:for all networks:
#      - bubblenet
#  elasticsearch:
#    build:
#      context: infrastructure/elasticsearch/
#    volumes:
#      - ./infrastructure/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    environment:
#      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
#  kibana:
#    build:
#      context: infrastructure/kibana/
#    container_name: kibana
#    volumes:
#      - ./infrastructure/kibana/config/:/usr/share/kibana/config:ro
#    ports:
#      - "5601:5601"
#    links:
#      - elasticsearch
#    depends_on:
#      - elasticsearch
#  logstash:
#    build:
#      context: infrastructure/logstash/
#    volumes:
#      - ./infrastructure/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
#      - ./infrastructure/logstash/pipeline:/usr/share/logstash/pipeline:ro
#    ports:
#      - "5000:5000"
#    environment:
#      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
#    depends_on:
#      - elasticsearch
  kafka-lenses-dev:
    build:
      context: infrastructure/kafka/
    container_name: news-aggregator_kafka
    privileged: true
    ports:
      - "3030:3030"
      - "2181:2181"
      - "9092:9092"
      - "8081:8081"
    environment:
      - SAMPLEDATA=0
      - ENABLE_SSL=0
      - CONNECT_HEAP=2G
      - DEBUG=1
      - KAFKA_ADVERTISED_HOST_NAME=kafka-lenses-dev
      - KAFKA_BROKER_ID = 999
    networks:
      - bubblenet
  news-producer:
    build:
      context: ./news-producer/
      dockerfile: Dockerfile
    container_name: news-producer
    ports:
       - "8080:8080"
       - "5005:5005"
    environment:
      JAVA_OPTS: "-Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
      JPDA_ADDRESS: "5005"
      JPDA_TRANSPORT: "dt_socket"
    depends_on:
      - kafka-lenses-dev
    links:
      - kafka-lenses-dev
    image: 'me.bubbleinvestor/news-producer:latest'
    networks:
      - bubblenet
  news-inference-engine:
    build:
      context: ./news-inference-engine/
      dockerfile: Dockerfile
    container_name: news-inference-engine
    ports:
      - "8181:8080"
    depends_on:
      - kafka-lenses-dev
    links:
      - kafka-lenses-dev
    image: 'me.bubbleinvestor/news-inference-engine:latest'
    networks:
      - bubblenet

networks:
  bubblenet:
    driver: bridge