logging:
  level:
    .: error
    org.springframework: ERROR
    me.bubbleinvestor: TRACE
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  profiles:
    active: "dev"
  main:
    banner-mode: "off"